apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: charts/helmapps/canary
    repoURL: git@github.com:kmrootkmrootxliu/argotest.git
    targetRevision: main

#    helm:
#      valueFiles:
#      - ./values.yaml

