apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 
    namespace: argocd
  project: default
  source:
    path: charts/helmapps/helm-guestbook
    repoURL: git@github.com:kmrootkmrootxliu/argotest.git
    targetRevision: master

    helm:
      valueFiles:
      - ./values.yaml

