apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: charts/apps
    repoURL: git@github.com:kmrootkmrootxliu/argotest.git
    targetRevision: HEAD
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
